// Species editor — convert an imported `.glb` into AEONS cells.
//
// This is the voxelization step: it rebuilds the imported (and
// user-scaled) mesh out of AEONS rhombic-dodecahedron cells of fixed
// size and fixed orientation, so every generated cell snaps to its
// neighbours exactly as the growth module's cells do (no gaps).
//
// ── Mathematical foundation ───────────────────────────────────────────────────
//
// A rhombic dodecahedron is the Voronoi cell of the FCC lattice, and RD
// cells tile 3-space with no gaps. So the cell CENTRES that the growth
// module places (`centre + SLOT_DIRS[i] * center_scale(EDGE_LEN)`) are
// exactly the points of an FCC lattice. That lattice is generated by the
// three face-diagonal basis vectors
//
//     b1 = a·(½,½,0)   b2 = a·(½,0,½)   b3 = a·(0,½,½)      a = 4·EDGE_LEN/√3
//
// and every one of the 18 `SLOT_DIRS` neighbour offsets is an integer
// combination of b1,b2,b3 (e.g. a·(1,0,0) = b1+b2−b3), so the set of all
// integer combinations `i·b1 + j·b2 + k·b3` is precisely the snap-grid the
// growth module uses. We anchor the lattice at the imported mesh's origin
// (the orange dot at `SPECIES_EDITOR_ORIGIN`), so site (0,0,0) sits on the
// dot — the requested seed.
//
// Fill rule (exactly as specified): a cell is placed at a lattice site iff
// the site's CENTRE lies inside the closed hull of the imported mesh.
// Insideness is a parity (even-odd) ray-cast against the mesh triangles.
// We enumerate every lattice site whose centre lies in the mesh's AABB and
// keep the ones inside the hull — equivalent to flood-filling outward from
// the centre, but robust to concavities and to the origin sitting in a
// pocket.
//
// The result becomes a single "Base Body" part with a `NoSymmetry` OCG
// (body parts / appendages / bilateral encoding are intentionally out of
// scope here). The cell type is taken from the Metabolism cycler.

use bevy::math::Mat3;
use bevy::mesh::{Indices, Mesh, PrimitiveTopology, VertexAttributeValues};
use bevy::prelude::*;

use crate::cell::CellType;
use crate::colony::Symmetry;
use crate::frontend::PANEL_BG_COLOR;
use crate::simulation_settings::WindowMode;

use super::mesh_import::MeshImport;
use super::session::{EditorBodyPart, SpeciesSession};
use super::SPECIES_EDITOR_ORIGIN;


// ── Tunables ─────────────────────────────────────────────────────────────────

/// Edge length of the AEONS cell (matches `volumetric_growth::EDGE_LEN`).
const EDGE_LEN: f32 = 1.0;

/// Safety ceiling on generated cells so a huge / over-scaled mesh can't
/// lock the UI thread. If hit, the fill stops early with a warning.
const MAX_CONVERT_CELLS: usize = 20_000;

/// Fixed, deliberately-skewed ray direction for the even-odd insideness
/// test. Off every axis and face-diagonal so it rarely grazes a triangle
/// edge of an axis-aligned mesh.
const RAY_DIR: Vec3 = Vec3::new(0.215_97, 0.364_79, 0.906_19);

const BTN_BG:       Color = Color::srgb(0.18, 0.48, 0.52);
const BTN_BG_HOVER: Color = Color::srgb(0.24, 0.60, 0.66);


// ── Marker ─────────────────────────────────────────────────────────────────────

#[derive(Component, Default)]
pub struct ConvertButton;


// ── Spawn (called from `spawn_overlay_panels`) ─────────────────────────────────

/// Spawn the "Convert to AEONS Cells" button, anchored bottom-left over the
/// bottom panel. Hidden by default; `manage_convert_button_visibility` shows
/// it only while a `.glb` is loaded.
pub fn spawn_convert_button(parent: &mut ChildSpawnerCommands) {
    parent
        .spawn((
            ConvertButton,
            Button,
            Node {
                position_type:   PositionType::Absolute,
                left:            Val::Px(14.0),
                bottom:          Val::Px(25.0),
                width:           Val::Px(200.0),
                height:          Val::Px(40.0),
                align_items:     AlignItems::Center,
                justify_content: JustifyContent::Center,
                display:         Display::None, // shown only when a glb is loaded
                ..default()
            },
            BackgroundColor(BTN_BG),
            GlobalZIndex(40),
        ))
        .with_children(|b| {
            b.spawn((
                Text::new("Convert to AEONS Cells"),
                TextFont { font_size: 14.0, ..default() },
                TextColor(Color::WHITE),
                Pickable::IGNORE,
            ));
        });
    let _ = PANEL_BG_COLOR; // (kept import parity with sibling panels)
}

/// Show the button only in SpeciesEditor mode with a mesh loaded.
pub fn manage_convert_button_visibility(
    mode:   Res<WindowMode>,
    mesh:   Res<MeshImport>,
    mut q:  Query<&mut Node, With<ConvertButton>>,
) {
    let want = *mode == WindowMode::SpeciesEditor && mesh.active();
    for mut node in &mut q {
        let target = if want { Display::Flex } else { Display::None };
        if node.display != target { node.display = target; }
    }
}


// ── Conversion handler ─────────────────────────────────────────────────────────

#[allow(clippy::too_many_arguments)]
pub fn handle_convert_button(
    mode:             Res<WindowMode>,
    mut interactions: Query<(&Interaction, &mut BackgroundColor),
                            (Changed<Interaction>, With<ConvertButton>)>,
    mesh_import:      Res<MeshImport>,
    meshes:           Res<Assets<Mesh>>,
    mesh_q:           Query<(&Mesh3d, &GlobalTransform)>,
    children_q:       Query<&Children>,
    mut session:      ResMut<SpeciesSession>,
) {
    if *mode != WindowMode::SpeciesEditor { return; }

    for (interaction, mut bg) in &mut interactions {
        match *interaction {
            Interaction::Pressed => {
                *bg = BackgroundColor(BTN_BG_HOVER);
                let Some(root) = mesh_import.root else { continue };
                convert(root, &meshes, &mesh_q, &children_q, &mut session);
            }
            Interaction::Hovered => *bg = BackgroundColor(BTN_BG_HOVER),
            Interaction::None    => *bg = BackgroundColor(BTN_BG),
        }
    }
}

/// Gather world-space triangles, voxelize onto the FCC lattice, and write
/// the result into the session as a single base body part.
fn convert(
    root:       Entity,
    meshes:     &Assets<Mesh>,
    mesh_q:     &Query<(&Mesh3d, &GlobalTransform)>,
    children_q: &Query<&Children>,
    session:    &mut SpeciesSession,
) {
    // 1. Collect every world-space triangle of the imported scene.
    let mut tris: Vec<[Vec3; 3]> = Vec::new();
    let mut stack = vec![root];
    while let Some(e) = stack.pop() {
        if let Ok(children) = children_q.get(e) {
            stack.extend(children.iter());
        }
        if let Ok((mesh3d, gx)) = mesh_q.get(e) {
            if let Some(mesh) = meshes.get(&mesh3d.0) {
                extract_triangles(mesh, gx, &mut tris);
            }
        }
    }
    if tris.is_empty() {
        warn!("convert: imported mesh has no triangles yet (still loading?) — aborting");
        return;
    }

    // 2. World AABB → local AABB (relative to the editor origin / dot).
    let mut lo = Vec3::splat(f32::INFINITY);
    let mut hi = Vec3::splat(f32::NEG_INFINITY);
    for t in &tris {
        for v in t {
            lo = lo.min(*v);
            hi = hi.max(*v);
        }
    }
    let lo_local = lo - SPECIES_EDITOR_ORIGIN;
    let hi_local = hi - SPECIES_EDITOR_ORIGIN;

    // 3. FCC lattice basis (anchored at the origin / dot = site (0,0,0)).
    let a = 4.0 * EDGE_LEN / 3.0_f32.sqrt(); // == dodecahedron::center_scale(EDGE_LEN)
    let b1 = Vec3::new(0.5, 0.5, 0.0) * a;
    let b2 = Vec3::new(0.5, 0.0, 0.5) * a;
    let b3 = Vec3::new(0.0, 0.5, 0.5) * a;
    let basis = Mat3::from_cols(b1, b2, b3);
    let inv = basis.inverse();

    // Integer (i,j,k) range covering the local AABB (pad by 1 each side).
    let mut imin = Vec3::splat(f32::INFINITY);
    let mut imax = Vec3::splat(f32::NEG_INFINITY);
    for &cx in &[lo_local.x, hi_local.x] {
        for &cy in &[lo_local.y, hi_local.y] {
            for &cz in &[lo_local.z, hi_local.z] {
                let ijk = inv * Vec3::new(cx, cy, cz);
                imin = imin.min(ijk);
                imax = imax.max(ijk);
            }
        }
    }
    let (i0, i1) = (imin.x.floor() as i64 - 1, imax.x.ceil() as i64 + 1);
    let (j0, j1) = (imin.y.floor() as i64 - 1, imax.y.ceil() as i64 + 1);
    let (k0, k1) = (imin.z.floor() as i64 - 1, imax.z.ceil() as i64 + 1);

    // 4. Enumerate lattice sites; keep those whose centre is inside the hull.
    let ct = session.draft.metabolism.starter_cell_type();
    let mut ocg: Vec<(usize, Vec3, CellType)> = Vec::new();
    let mut capped = false;
    'fill: for i in i0..=i1 {
        for j in j0..=j1 {
            for k in k0..=k1 {
                let local = basis * Vec3::new(i as f32, j as f32, k as f32);
                // Cheap AABB reject — outside the box can't be inside the hull.
                if local.x < lo_local.x || local.x > hi_local.x
                    || local.y < lo_local.y || local.y > hi_local.y
                    || local.z < lo_local.z || local.z > hi_local.z
                {
                    continue;
                }
                let world = SPECIES_EDITOR_ORIGIN + local;
                if point_inside_mesh(world, &tris) {
                    ocg.push((ocg.len(), local, ct));
                    if ocg.len() >= MAX_CONVERT_CELLS {
                        capped = true;
                        break 'fill;
                    }
                }
            }
        }
    }

    if ocg.is_empty() {
        warn!("convert: no lattice centre fell inside the mesh hull — \
               try scaling the mesh larger before converting");
        return;
    }
    if capped {
        warn!("convert: hit the {}-cell safety cap; result is truncated. \
               Scale the mesh smaller for a complete fill.", MAX_CONVERT_CELLS);
    }

    // 5. Write the result: one base body, full-solid OCG, NoSymmetry. Setting
    // `body_parts` non-empty makes `mesh_import::sync_with_session` drop the
    // glb on the next frame, and trips `refresh_species_mesh` to render the
    // new cell body. Normal cell editing resumes (placement ungates).
    session.draft.symmetry      = Symmetry::NoSymmetry;
    session.body_parts          = vec![EditorBodyPart {
        name:    "Base Body".to_string(),
        ocg,
        is_limb: false,
        parent:  0,
    }];
    session.active_body_part    = 0;
    session.selected_cell_type  = Some(ct);
    session.first_cell_spawned  = true;
    session.dirty               = true;

    info!(
        "convert: voxelized imported mesh into {} AEONS cells (NoSymmetry, {:?})",
        session.body_parts[0].ocg.len(), ct,
    );
}


// ── Geometry helpers ───────────────────────────────────────────────────────────

/// Append a mesh's world-space triangles to `out` (mirrors
/// `world_geometry::extract_triangles`).
fn extract_triangles(mesh: &Mesh, global: &GlobalTransform, out: &mut Vec<[Vec3; 3]>) {
    if mesh.primitive_topology() != PrimitiveTopology::TriangleList {
        return;
    }
    let positions = match mesh.attribute(Mesh::ATTRIBUTE_POSITION) {
        Some(VertexAttributeValues::Float32x3(p)) => p,
        _ => return,
    };
    let xform = |i: usize| -> Vec3 {
        let p = positions[i];
        global.transform_point(Vec3::new(p[0], p[1], p[2]))
    };
    let push = |a: usize, b: usize, c: usize, out: &mut Vec<[Vec3; 3]>| {
        if a < positions.len() && b < positions.len() && c < positions.len() {
            out.push([xform(a), xform(b), xform(c)]);
        }
    };
    match mesh.indices() {
        Some(Indices::U32(idx)) => {
            for t in idx.chunks_exact(3) { push(t[0] as usize, t[1] as usize, t[2] as usize, out); }
        }
        Some(Indices::U16(idx)) => {
            for t in idx.chunks_exact(3) { push(t[0] as usize, t[1] as usize, t[2] as usize, out); }
        }
        None => {
            let n = positions.len() - (positions.len() % 3);
            for i in (0..n).step_by(3) { push(i, i + 1, i + 2, out); }
        }
    }
}

/// Even-odd insideness test: count ray/triangle crossings from `p` along
/// `RAY_DIR`; odd ⇒ inside the closed hull.
fn point_inside_mesh(p: Vec3, tris: &[[Vec3; 3]]) -> bool {
    let mut crossings = 0u32;
    for t in tris {
        if ray_hits_tri(p, RAY_DIR, t[0], t[1], t[2]) {
            crossings += 1;
        }
    }
    crossings & 1 == 1
}

/// Möller–Trumbore ray/triangle intersection. Returns true for a hit at a
/// strictly positive distance along `dir`.
fn ray_hits_tri(orig: Vec3, dir: Vec3, a: Vec3, b: Vec3, c: Vec3) -> bool {
    let e1 = b - a;
    let e2 = c - a;
    let pvec = dir.cross(e2);
    let det = e1.dot(pvec);
    if det.abs() < 1e-9 {
        return false; // ray parallel to triangle
    }
    let inv_det = 1.0 / det;
    let tvec = orig - a;
    let u = tvec.dot(pvec) * inv_det;
    if !(0.0..=1.0).contains(&u) {
        return false;
    }
    let qvec = tvec.cross(e1);
    let v = dir.dot(qvec) * inv_det;
    if v < 0.0 || u + v > 1.0 {
        return false;
    }
    let dist = e2.dot(qvec) * inv_det;
    dist > 1e-6
}
