// Species editor — voxelize an imported `.glb` into AEONS cells.
//
// Why FCC: a rhombic dodecahedron is the Voronoi cell of the FCC lattice and RD
// cells tile space gaplessly, so the growth module's cell centres are exactly
// FCC lattice points, generated by the face-diagonal basis
//     b1 = a·(½,½,0)   b2 = a·(½,0,½)   b3 = a·(0,½,½)      a = 4·EDGE_LEN/√3
// Every one of the 18 `SLOT_DIRS` neighbour offsets is an integer combination of
// b1,b2,b3, so integer combinations `i·b1 + j·b2 + k·b3` reproduce the growth
// module's snap-grid. Lattice anchored at `SPECIES_EDITOR_ORIGIN` → site (0,0,0)
// is the seed.
//
// Fill rule: place a cell iff the site centre lies inside the mesh's closed hull
// (even-odd ray-cast). Enumerate every site in the AABB and keep the inside ones
// — robust to concavities and an origin sitting in a pocket.
//
// MULTI-PART: an imported `.glb` may hold several sub-meshes that are not
// connected by edges (separate Blender objects, or disjoint islands within one
// mesh). Each connected component (found by welding coincident vertices and
// union-finding triangles that share one) is voxelized into its OWN part. The
// largest part (most cells) is auto-picked as the base body; every other part
// becomes an appendage whose `parent` is computed by a minimum-spanning-tree
// rooted at the base (each part hangs off the already-connected part whose
// CENTRE is nearest). Each appendage's OCG is reordered so its FIRST cell — the
// runtime attachment pivot / rotation point — is the cell nearest its parent's
// centre. The user re-assigns (limb toggle, rename) via the Body-part panel.
// A single-component mesh degrades to the old one-part behaviour.
// All parts are NoSymmetry; cell type from the Metabolism cycler.

use std::collections::{HashMap, VecDeque};

use bevy::math::Mat3;
use bevy::mesh::{Indices, Mesh, PrimitiveTopology, VertexAttributeValues};
use bevy::prelude::*;

use crate::cell::CellType;
use crate::colony::Symmetry;
use crate::frontend::PANEL_BG_COLOR;
use crate::simulation_settings::WindowMode;

use super::mesh_import::MeshImport;
use super::session::{EditorBodyPart, SpeciesSession};
use super::SPECIES_EDITOR_ORIGIN;


// ── Tunables ─────────────────────────────────────────────────────────────────

/// Edge length of the AEONS cell (matches `volumetric_growth::EDGE_LEN`).
const EDGE_LEN: f32 = 1.0;

/// Safety ceiling so an over-scaled mesh can't lock the UI thread; the fill
/// stops early with a warning when hit.
const MAX_CONVERT_CELLS: usize = 20_000;

/// Deliberately-skewed ray direction for the even-odd test — off every axis and
/// face-diagonal so it rarely grazes a triangle edge of an axis-aligned mesh.
const RAY_DIR: Vec3 = Vec3::new(0.215_97, 0.364_79, 0.906_19);

const BTN_BG:       Color = Color::srgb(0.18, 0.48, 0.52);
const BTN_BG_HOVER: Color = Color::srgb(0.24, 0.60, 0.66);


// ── Marker ─────────────────────────────────────────────────────────────────────

#[derive(Component, Default)]
pub struct ConvertButton;


// ── Spawn (called from `spawn_overlay_panels`) ─────────────────────────────────

/// Spawn the "Convert to AEONS Cells" button (bottom-left). Hidden until a
/// `.glb` is loaded (see `manage_convert_button_visibility`).
pub fn spawn_convert_button(parent: &mut ChildSpawnerCommands) {
    parent
        .spawn((
            ConvertButton,
            Button,
            Node {
                position_type:   PositionType::Absolute,
                left:            Val::Px(14.0),
                bottom:          Val::Px(25.0),
                width:           Val::Px(200.0),
                height:          Val::Px(40.0),
                align_items:     AlignItems::Center,
                justify_content: JustifyContent::Center,
                display:         Display::None, // shown only when a glb is loaded
                ..default()
            },
            BackgroundColor(BTN_BG),
            GlobalZIndex(40),
        ))
        .with_children(|b| {
            b.spawn((
                Text::new("Convert to AEONS Cells"),
                TextFont { font_size: 14.0, ..default() },
                TextColor(Color::WHITE),
                Pickable::IGNORE,
            ));
        });
    let _ = PANEL_BG_COLOR; // import parity with sibling panels
}

/// Show the button only in SpeciesEditor mode with a mesh loaded.
pub fn manage_convert_button_visibility(
    mode:   Res<WindowMode>,
    mesh:   Res<MeshImport>,
    mut q:  Query<&mut Node, With<ConvertButton>>,
) {
    let want = *mode == WindowMode::SpeciesEditor && mesh.active();
    for mut node in &mut q {
        let target = if want { Display::Flex } else { Display::None };
        if node.display != target { node.display = target; }
    }
}


// ── Conversion handler ─────────────────────────────────────────────────────────

#[allow(clippy::too_many_arguments)]
pub fn handle_convert_button(
    mode:             Res<WindowMode>,
    mut interactions: Query<(&Interaction, &mut BackgroundColor),
                            (Changed<Interaction>, With<ConvertButton>)>,
    mesh_import:      Res<MeshImport>,
    meshes:           Res<Assets<Mesh>>,
    mesh_q:           Query<(&Mesh3d, &GlobalTransform)>,
    children_q:       Query<&Children>,
    mut session:      ResMut<SpeciesSession>,
) {
    if *mode != WindowMode::SpeciesEditor { return; }

    for (interaction, mut bg) in &mut interactions {
        match *interaction {
            Interaction::Pressed => {
                *bg = BackgroundColor(BTN_BG_HOVER);
                let Some(root) = mesh_import.root else { continue };
                convert(root, &meshes, &mesh_q, &children_q, &mut session);
            }
            Interaction::Hovered => *bg = BackgroundColor(BTN_BG_HOVER),
            Interaction::None    => *bg = BackgroundColor(BTN_BG),
        }
    }
}

/// Gather world-space triangles, split them into edge-disconnected components,
/// voxelize each onto the shared FCC lattice, and write the result into the
/// session as one base body part plus an MST-rooted appendage hierarchy.
fn convert(
    root:       Entity,
    meshes:     &Assets<Mesh>,
    mesh_q:     &Query<(&Mesh3d, &GlobalTransform)>,
    children_q: &Query<&Children>,
    session:    &mut SpeciesSession,
) {
    // 1. Collect every world-space triangle of the imported scene.
    let mut tris: Vec<[Vec3; 3]> = Vec::new();
    let mut stack = vec![root];
    while let Some(e) = stack.pop() {
        if let Ok(children) = children_q.get(e) {
            stack.extend(children.iter());
        }
        if let Ok((mesh3d, gx)) = mesh_q.get(e) {
            if let Some(mesh) = meshes.get(&mesh3d.0) {
                extract_triangles(mesh, gx, &mut tris);
            }
        }
    }
    if tris.is_empty() {
        warn!("convert: imported mesh has no triangles yet (still loading?) — aborting");
        return;
    }

    // 2. Split into edge-disconnected components (each = one future part). A
    // single-component mesh yields one group → the old one-part behaviour.
    let components = connected_components(&tris);
    let comp_tris: Vec<Vec<[Vec3; 3]>> = components
        .iter()
        .map(|g| g.iter().map(|&ti| tris[ti]).collect())
        .collect();

    // 3. Global AABB (shared by every component so all parts land in one frame).
    let mut lo = Vec3::splat(f32::INFINITY);
    let mut hi = Vec3::splat(f32::NEG_INFINITY);
    for t in &tris {
        for v in t {
            lo = lo.min(*v);
            hi = hi.max(*v);
        }
    }
    let lo_local = lo - SPECIES_EDITOR_ORIGIN;
    let hi_local = hi - SPECIES_EDITOR_ORIGIN;

    // 4. FCC lattice basis (anchored at the origin / dot = site (0,0,0)).
    let a = 4.0 * EDGE_LEN / 3.0_f32.sqrt(); // == dodecahedron::center_scale(EDGE_LEN)
    let b1 = Vec3::new(0.5, 0.5, 0.0) * a;
    let b2 = Vec3::new(0.5, 0.0, 0.5) * a;
    let b3 = Vec3::new(0.0, 0.5, 0.5) * a;
    let basis = Mat3::from_cols(b1, b2, b3);
    let inv = basis.inverse();

    // Integer (i,j,k) range covering the local AABB (pad by 1 each side).
    let mut imin = Vec3::splat(f32::INFINITY);
    let mut imax = Vec3::splat(f32::NEG_INFINITY);
    for &cx in &[lo_local.x, hi_local.x] {
        for &cy in &[lo_local.y, hi_local.y] {
            for &cz in &[lo_local.z, hi_local.z] {
                let ijk = inv * Vec3::new(cx, cy, cz);
                imin = imin.min(ijk);
                imax = imax.max(ijk);
            }
        }
    }
    let (i0, i1) = (imin.x.floor() as i64 - 1, imax.x.ceil() as i64 + 1);
    let (j0, j1) = (imin.y.floor() as i64 - 1, imax.y.ceil() as i64 + 1);
    let (k0, k1) = (imin.z.floor() as i64 - 1, imax.z.ceil() as i64 + 1);

    // 5. Enumerate lattice sites once; assign each inside-site to the FIRST
    // component whose hull contains it (disjoint meshes ⇒ at most one). Each
    // component accrues its own OCG; the cap is global across all parts.
    let ct = session.draft.metabolism.starter_cell_type();
    let mut comp_ocg: Vec<Vec<(usize, Vec3, CellType)>> = vec![Vec::new(); comp_tris.len()];
    let mut total = 0usize;
    let mut capped = false;
    'fill: for i in i0..=i1 {
        for j in j0..=j1 {
            for k in k0..=k1 {
                let local = basis * Vec3::new(i as f32, j as f32, k as f32);
                // Cheap AABB reject — outside the box can't be inside any hull.
                if local.x < lo_local.x || local.x > hi_local.x
                    || local.y < lo_local.y || local.y > hi_local.y
                    || local.z < lo_local.z || local.z > hi_local.z
                {
                    continue;
                }
                let world = SPECIES_EDITOR_ORIGIN + local;
                for (ci, ctris) in comp_tris.iter().enumerate() {
                    if point_inside_mesh(world, ctris) {
                        let n = comp_ocg[ci].len();
                        comp_ocg[ci].push((n, local, ct));
                        total += 1;
                        if total >= MAX_CONVERT_CELLS {
                            capped = true;
                            break 'fill;
                        }
                        break; // one owner per site
                    }
                }
            }
        }
    }

    // Drop components whose hull caught no lattice centre (sliver / open surface).
    let parts_ocg: Vec<Vec<(usize, Vec3, CellType)>> =
        comp_ocg.into_iter().filter(|o| !o.is_empty()).collect();
    if parts_ocg.is_empty() {
        warn!("convert: no lattice centre fell inside any mesh hull — \
               try scaling the mesh larger before converting");
        return;
    }
    if capped {
        warn!("convert: hit the {}-cell safety cap; result is truncated. \
               Scale the mesh smaller for a complete fill.", MAX_CONVERT_CELLS);
    }

    // 6. Build the body parts. One component → a single base body; several →
    // base (most cells) + MST-rooted appendage hierarchy. Non-empty
    // `body_parts` makes `mesh_import::sync_with_session` drop the glb next
    // frame and trips `refresh_species_mesh`; cell editing resumes.
    session.draft.symmetry = Symmetry::NoSymmetry;
    let body_parts = build_body_parts(parts_ocg);
    let n_parts = body_parts.len();
    let n_cells: usize = body_parts.iter().map(|p| p.ocg.len()).sum();
    session.body_parts          = body_parts;
    session.active_body_part    = 0;
    session.selected_cell_type  = Some(ct);
    session.first_cell_spawned  = true;
    session.dirty               = true;

    info!(
        "convert: voxelized imported mesh into {} part(s), {} AEONS cells \
         (NoSymmetry, {:?})",
        n_parts, n_cells, ct,
    );
}


// ── Multi-part hierarchy ─────────────────────────────────────────────────────

/// Turn the per-component OCGs into the session's body-part list.
///
/// One component → a single "Base Body" part (degrades to the old behaviour).
/// Several → the largest component (most cells) is the base; every other part
/// hangs off the already-connected part whose CENTROID is nearest (a
/// minimum-spanning-tree rooted at the base). Parts are emitted in BFS order so
/// each parent precedes its children (the spawn path requires `parent <= index`
/// for NoSymmetry). Every appendage's OCG is reordered so the cell nearest its
/// parent's centroid is index 0 — that first cell is the runtime attachment
/// pivot / rotation point. Appendages default to `is_limb = false` (organs);
/// the user toggles limbs in the Body-part panel.
fn build_body_parts(parts_ocg: Vec<Vec<(usize, Vec3, CellType)>>) -> Vec<EditorBodyPart> {
    let n = parts_ocg.len();
    if n == 1 {
        return vec![EditorBodyPart {
            name:    "Base Body".to_string(),
            ocg:     renumber(parts_ocg.into_iter().next().unwrap()),
            is_limb: false,
            parent:  0,
        }];
    }

    let centroids: Vec<Vec3> = parts_ocg
        .iter()
        .map(|o| o.iter().map(|(_, p, _)| *p).sum::<Vec3>() / o.len() as f32)
        .collect();

    // Base = component with the most cells.
    let base = (0..n).max_by_key(|&i| parts_ocg[i].len()).unwrap();

    // Prim MST rooted at the base: `parent_of[c]` = nearest already-in-tree part.
    let mut parent_of = vec![usize::MAX; n];
    let mut in_tree = vec![false; n];
    in_tree[base] = true;
    parent_of[base] = base;
    for _ in 1..n {
        let mut best: Option<(f32, usize, usize)> = None; // (dist², child, parent)
        for c in (0..n).filter(|&c| !in_tree[c]) {
            for p in (0..n).filter(|&p| in_tree[p]) {
                let d = centroids[c].distance_squared(centroids[p]);
                if best.map_or(true, |(b, _, _)| d < b) {
                    best = Some((d, c, p));
                }
            }
        }
        let (_, c, p) = best.unwrap();
        in_tree[c] = true;
        parent_of[c] = p;
    }

    // BFS from the base → emission order with every parent before its children.
    let mut children: Vec<Vec<usize>> = vec![Vec::new(); n];
    for c in (0..n).filter(|&c| c != base) {
        children[parent_of[c]].push(c);
    }
    let mut order = Vec::with_capacity(n);
    let mut queue = VecDeque::from([base]);
    while let Some(node) = queue.pop_front() {
        order.push(node);
        for &ch in &children[node] {
            queue.push_back(ch);
        }
    }
    let mut new_idx = vec![0usize; n];
    for (new, &old) in order.iter().enumerate() {
        new_idx[old] = new;
    }

    // Build parts in BFS order, remapping parents and seating the first cell.
    order
        .iter()
        .enumerate()
        .map(|(new, &old)| {
            let is_base = old == base;
            let mut ocg = parts_ocg[old].clone();
            let parent = if is_base { 0 } else { new_idx[parent_of[old]] };
            if !is_base {
                // First cell = the one nearest the PARENT'S centre (the runtime
                // rotation point). Move it to index 0; renumber drops the rest.
                let pc = centroids[parent_of[old]];
                if let Some(closest) = (0..ocg.len()).min_by(|&a, &b| {
                    ocg[a].1.distance_squared(pc)
                        .total_cmp(&ocg[b].1.distance_squared(pc))
                }) {
                    ocg.swap(0, closest);
                }
            }
            EditorBodyPart {
                name: if is_base { "Base Body".to_string() } else { format!("Body Part {new}") },
                ocg: renumber(ocg),
                is_limb: false,
                parent,
            }
        })
        .collect()
}

/// Re-index an OCG's entries sequentially 0..N (positions/types unchanged).
fn renumber(mut ocg: Vec<(usize, Vec3, CellType)>) -> Vec<(usize, Vec3, CellType)> {
    for (i, e) in ocg.iter_mut().enumerate() {
        e.0 = i;
    }
    ocg
}


// ── Connected components (vertex weld + union-find) ──────────────────────────

/// Group the triangles into edge-disconnected components: weld coincident
/// vertices (so triangles that share a corner are recognised as touching),
/// union-find the triangles that share a welded vertex, and return one
/// `Vec<triangle index>` per component. Handles both separate glb mesh nodes
/// and disjoint islands inside a single mesh.
fn connected_components(tris: &[[Vec3; 3]]) -> Vec<Vec<usize>> {
    // Weld tolerance scaled to model size (Blender shares exact coords for
    // joined verts; a tiny relative epsilon absorbs float drift without
    // fusing two meshes separated by a visible gap).
    let mut lo = Vec3::splat(f32::INFINITY);
    let mut hi = Vec3::splat(f32::NEG_INFINITY);
    for t in tris {
        for v in t {
            lo = lo.min(*v);
            hi = hi.max(*v);
        }
    }
    let eps = ((hi - lo).length() * 1e-4).max(1e-4);

    let mut buckets: HashMap<(i64, i64, i64), Vec<(usize, Vec3)>> = HashMap::new();
    let mut verts: Vec<Vec3> = Vec::new();
    let mut tri_vids: Vec<[usize; 3]> = Vec::with_capacity(tris.len());
    for t in tris {
        tri_vids.push([
            weld_vertex(t[0], eps, &mut buckets, &mut verts),
            weld_vertex(t[1], eps, &mut buckets, &mut verts),
            weld_vertex(t[2], eps, &mut buckets, &mut verts),
        ]);
    }

    let mut uf = UnionFind::new(verts.len());
    for v in &tri_vids {
        uf.union(v[0], v[1]);
        uf.union(v[1], v[2]);
    }

    let mut groups: HashMap<usize, Vec<usize>> = HashMap::new();
    for (ti, v) in tri_vids.iter().enumerate() {
        groups.entry(uf.find(v[0])).or_default().push(ti);
    }
    groups.into_values().collect()
}

/// Return the welded-vertex id for `p`: reuse an existing vertex within `eps`
/// (searching the 3×3×3 neighbourhood of grid buckets so a point straddling a
/// bucket boundary still matches), else mint a new one.
fn weld_vertex(
    p:       Vec3,
    eps:     f32,
    buckets: &mut HashMap<(i64, i64, i64), Vec<(usize, Vec3)>>,
    verts:   &mut Vec<Vec3>,
) -> usize {
    let inv = 1.0 / eps;
    let (kx, ky, kz) = ((p.x * inv).round() as i64, (p.y * inv).round() as i64, (p.z * inv).round() as i64);
    let e2 = eps * eps;
    for dx in -1..=1 {
        for dy in -1..=1 {
            for dz in -1..=1 {
                if let Some(list) = buckets.get(&(kx + dx, ky + dy, kz + dz)) {
                    for &(id, q) in list {
                        if (q - p).length_squared() <= e2 {
                            return id;
                        }
                    }
                }
            }
        }
    }
    let id = verts.len();
    verts.push(p);
    buckets.entry((kx, ky, kz)).or_default().push((id, p));
    id
}

/// Minimal union-find with path-halving — groups welded vertices into the
/// connected components their triangles form.
struct UnionFind {
    parent: Vec<usize>,
}

impl UnionFind {
    fn new(n: usize) -> Self {
        Self { parent: (0..n).collect() }
    }
    fn find(&mut self, mut x: usize) -> usize {
        while self.parent[x] != x {
            self.parent[x] = self.parent[self.parent[x]];
            x = self.parent[x];
        }
        x
    }
    fn union(&mut self, a: usize, b: usize) {
        let (ra, rb) = (self.find(a), self.find(b));
        if ra != rb {
            self.parent[ra] = rb;
        }
    }
}


// ── Geometry helpers ───────────────────────────────────────────────────────────

/// Append a mesh's world-space triangles to `out` (mirrors
/// `world_geometry::extract_triangles`).
fn extract_triangles(mesh: &Mesh, global: &GlobalTransform, out: &mut Vec<[Vec3; 3]>) {
    if mesh.primitive_topology() != PrimitiveTopology::TriangleList {
        return;
    }
    let positions = match mesh.attribute(Mesh::ATTRIBUTE_POSITION) {
        Some(VertexAttributeValues::Float32x3(p)) => p,
        _ => return,
    };
    let xform = |i: usize| -> Vec3 {
        let p = positions[i];
        global.transform_point(Vec3::new(p[0], p[1], p[2]))
    };
    let push = |a: usize, b: usize, c: usize, out: &mut Vec<[Vec3; 3]>| {
        if a < positions.len() && b < positions.len() && c < positions.len() {
            out.push([xform(a), xform(b), xform(c)]);
        }
    };
    match mesh.indices() {
        Some(Indices::U32(idx)) => {
            for t in idx.chunks_exact(3) { push(t[0] as usize, t[1] as usize, t[2] as usize, out); }
        }
        Some(Indices::U16(idx)) => {
            for t in idx.chunks_exact(3) { push(t[0] as usize, t[1] as usize, t[2] as usize, out); }
        }
        None => {
            let n = positions.len() - (positions.len() % 3);
            for i in (0..n).step_by(3) { push(i, i + 1, i + 2, out); }
        }
    }
}

/// Even-odd insideness test: count ray/triangle crossings from `p` along
/// `RAY_DIR`; odd ⇒ inside the closed hull.
fn point_inside_mesh(p: Vec3, tris: &[[Vec3; 3]]) -> bool {
    let mut crossings = 0u32;
    for t in tris {
        if ray_hits_tri(p, RAY_DIR, t[0], t[1], t[2]) {
            crossings += 1;
        }
    }
    crossings & 1 == 1
}

/// Möller–Trumbore ray/triangle intersection. Returns true for a hit at a
/// strictly positive distance along `dir`.
fn ray_hits_tri(orig: Vec3, dir: Vec3, a: Vec3, b: Vec3, c: Vec3) -> bool {
    let e1 = b - a;
    let e2 = c - a;
    let pvec = dir.cross(e2);
    let det = e1.dot(pvec);
    if det.abs() < 1e-9 {
        return false; // ray parallel to triangle
    }
    let inv_det = 1.0 / det;
    let tvec = orig - a;
    let u = tvec.dot(pvec) * inv_det;
    if !(0.0..=1.0).contains(&u) {
        return false;
    }
    let qvec = tvec.cross(e1);
    let v = dir.dot(qvec) * inv_det;
    if v < 0.0 || u + v > 1.0 {
        return false;
    }
    let dist = e2.dot(qvec) * inv_det;
    dist > 1e-6
}
