// Limb-based L3 brain — PPO pool for Level3 heterotrophs with
// `!Organism::movement_mode.is_sliding()`.
//
// Structurally identical to the herbivore_1 / L2 limb pools; only the
// enrolment filter (`IntelligenceLevel::Level3`) differs. Network sizes
// and PPO hyperparameters come from the shared `limb_ppo` engine.
//
// All the per-level boilerplate (the `BrainPoolL3Limb` / `BrainSlotL3Limb`
// newtypes, `FromWorld`, the enrolment/free/apply systems) is generated by the
// shared macros in `limb_ppo`; this file is just the two invocations supplying
// the differing tokens (level literal + type/fn names).

use crate::{define_limb_pool_assign, define_limb_pool_common};

define_limb_pool_common!(
    BrainPoolL3Limb,
    BrainSlotL3Limb,
    free_brains_l3_limb,
    apply_intelligence_level_3_limb,
);

define_limb_pool_assign!(
    assign_brains_l3_limb,
    BrainPoolL3Limb,
    BrainSlotL3Limb,
    Level3,
);
