// Limb-based herbivore_1 brain — PPO pool for Level1 + Heterotroph +
// non-Carnivore organisms with `!Organism::movement_mode.is_sliding()`.
//
// Mirrors the sliding herbivore_1 pool structurally but delegates the
// network, rollout buffer, GAE and PPO update to the shared `limb_ppo`
// engine, so the three per-level limb brains differ only in their
// enrolment filter.
//
// The boilerplate (the `BrainPoolHerbivore1Limb` / `BrainSlotHerbivore1Limb`
// newtypes, `FromWorld`, `free_brains_*`, `apply_intelligence_level_*`) is
// generated by the shared `define_limb_pool_common!` macro in `limb_ppo`. The
// `assign_brains_*` system and the `share_limb_policies_*` no-op are NOT
// macro-generated: this level carries the extra carnivore-exclusion filter and
// the STANDING_TASK / `--reload-limb-brains` restore branch that L2/L3 don't, so
// they're written out by hand below.

use bevy::prelude::*;

use std::collections::HashMap;

use crate::colony::{IntelligenceLevel, Organism, Heterotroph, Carnivore};
use crate::limb_ppo::BrainRestoreLimb;
use crate::define_limb_pool_common;


// ── Shared boilerplate (Slot + Pool + FromWorld + free + apply) ───────────────

define_limb_pool_common!(
    BrainPoolHerbivore1Limb,
    BrainSlotHerbivore1Limb,
    free_brains_herbivore_1_limb,
    apply_intelligence_level_herbivore_1_limb,
);


// ── Lifecycle: enrolment (level-specific) ─────────────────────────────────────

/// Enrol newly-spawned limb-based Level1 non-carnivore heterotrophs.
/// Mirrors the gating logic of the sliding pool, with the
/// `!movement_mode.is_sliding()` extra filter so the two populations are disjoint.
pub fn assign_brains_herbivore_1_limb(
    mut pool:     NonSendMut<BrainPoolHerbivore1Limb>,
    new:          Query<(Entity, &Organism, Option<&BrainRestoreLimb>, Option<&crate::rl_helpers::BrainInheritance>), (
        With<Heterotroph>,
        Without<Carnivore>,
        Without<BrainSlotHerbivore1Limb>,
    )>,
    reload_brains: Res<crate::simulation_settings::ReloadLimbBrains>,
    mut commands: Commands,
) {
    for (e, organism, restore, inheritance) in new.iter() {
        if !matches!(organism.intelligence_level, IntelligenceLevel::Level1) { continue; }
        if organism.movement_mode.is_sliding() { continue; }
        // Swimmers train in their own pool (intelligence_level_1_swimming).
        if organism.movement_mode.is_swimming() { continue; }
        // SimpleAquatic movers train in the basic_3d_movement pool (kinematic, no limbs).
        if organism.movement_mode.is_simple_aquatic() { continue; }
        let Some(s) = pool.0.enrol(e) else { continue };
        // STANDING task: by default ignore the saved Runner brains — they are
        // locomotion-trained and tanh-SATURATED (μ pinned at ±1 → zero actor
        // gradient → the policy can't move, the body freezes in one pose). Keep
        // the pool's fresh fan-in + neutral-init weights so PPO actually explores
        // and learns to stand. EXCEPTION: `--reload-limb-brains` (set when loading
        // a colony saved AFTER a standing run) restores the trained STANDING policy
        // through the normal restore path below — the durable-success artifact.
        if crate::simulation_settings::STANDING_TASK && !reload_brains.0 {
            if restore.is_some() { commands.entity(e).try_remove::<BrainRestoreLimb>(); }
            if inheritance.is_some() { commands.entity(e).try_remove::<crate::rl_helpers::BrainInheritance>(); }
            commands.entity(e).try_insert(BrainSlotHerbivore1Limb(s));
            continue;
        }
        // Saved weights (loaded `.colony`) → overwrite this organism's SPECIES
        // net (keyed by species_id, UNCLASSIFIED until first classified).
        if let Some(r) = restore {
            pool.0.restore_species(organism.species_id.unwrap_or(0), r);
            commands.entity(e).try_remove::<BrainRestoreLimb>();
        }
        // SHARED policy → no per-slot weight inheritance; a newborn of an
        // existing species already shares that species' trained net. Just clear
        // any inheritance marker so it isn't reprocessed.
        if inheritance.is_some() { commands.entity(e).try_remove::<crate::rl_helpers::BrainInheritance>(); }
        commands.entity(e).try_insert(BrainSlotHerbivore1Limb(s));
    }
}


// ── Social learning (population policy sharing) ───────────────────────────────

/// Every `SHARE_INTERVAL` of virtual time, copy the BEST walker's brain (max net
/// base displacement over the window) into the worst non-walkers, so the WHOLE
/// population converges to a walking policy that only a fraction of organisms
/// discover independently (PPO stragglers stuck in still/hop local optima). Net
/// displacement of the base body part is the "is it actually travelling" signal —
/// a hopper/spinner racks up little. Recipients keep training, so they refine the
/// inherited policy rather than freezing. Only shares when the best is genuinely
/// walking, so a bad policy is never propagated.
pub fn share_limb_policies_herbivore_1(
    _pool:          NonSendMut<BrainPoolHerbivore1Limb>,
    _slots:         Query<(Entity, &BrainSlotHerbivore1Limb)>,
    _base_parts:    Query<(&bevy::prelude::ChildOf, &crate::cell::BodyPartIndex, &bevy::prelude::GlobalTransform)>,
    _heightmap:     Option<Res<crate::world_geometry::HeightmapSampler>>,
    _time:          Res<bevy::prelude::Time<bevy::prelude::Virtual>>,
    _anchors:       Local<HashMap<Entity, Vec3>>,
    _next_share:    Local<f32>,
) {
    // NO-OP under the per-SPECIES shared-policy model. Social policy-copy across
    // individuals is now intrinsic: every organism of a species trains and uses
    // the SAME net, so a "best walker"'s improvement is shared with its whole
    // species automatically every PPO update — there is no per-slot weight to
    // copy. (Cross-species copying would be wrong: species hold deliberately
    // divergent policies.) The system is left registered (in `behaviour.rs`) but
    // does nothing; the per-species PPO update is the convergence mechanism.
}
