// Limb-based L2 brain — PPO pool for Level2 heterotrophs with
// `!Organism::movement_mode.is_sliding()`.
//
// Structurally identical to the herbivore_1 limb pool; only the
// enrolment filter (`IntelligenceLevel::Level2`) differs. Network sizes
// and PPO hyperparameters come from the shared `limb_ppo` engine.
//
// All the per-level boilerplate (the `BrainPoolL2Limb` / `BrainSlotL2Limb`
// newtypes, `FromWorld`, the enrolment/free/apply systems) is generated by the
// shared macros in `limb_ppo`; this file is just the two invocations supplying
// the differing tokens (level literal + type/fn names).

use crate::{define_limb_pool_assign, define_limb_pool_common};

define_limb_pool_common!(
    BrainPoolL2Limb,
    BrainSlotL2Limb,
    free_brains_l2_limb,
    apply_intelligence_level_2_limb,
);

define_limb_pool_assign!(
    assign_brains_l2_limb,
    BrainPoolL2Limb,
    BrainSlotL2Limb,
    Level2,
);
